version: '3.8'

services:
    pilosa-leader:
        image: 771945457201.dkr.ecr.us-west-2.amazonaws.com/audience-pilosa:latest
        networks:
        - pilosanetwork
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
        entrypoint: ./entrypoint_leader.sh
        volumes:
            - /mnt:/opt/pilosa/data
        ports:
          - target: 10101
            published: 10101
            mode: host
          - target: 11101
            published: 11101
            mode: host
          - target: 15001
            published: 15001
            mode: host
    pilosa-workers:
        image: 771945457201.dkr.ecr.us-west-2.amazonaws.com/audience-pilosa:latest
        networks:
        - pilosanetwork
        depends_on:
        - pilosa-leader
        deploy:
            replicas: ${NUM_WORKERS}
            placement:
                max_replicas_per_node: 1
            endpoint_mode: dnsrr
        entrypoint: ./entrypoint_workers.sh
        volumes:
            - /mnt:/opt/pilosa/data
        ports:
          - target: 10101
            published: 10101
            mode: host
          - target: 11101
            published: 11101
            mode: host
          - target: 15001
            published: 15001
            mode: host

networks:
    pilosanetwork:
        driver: overlay
        attachable: true
