version: '3.8'

services:
    pilosa-leader:
        image: audience-pilosa:latest
        networks:
        - pilosanetwork
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
        entrypoint: ./entrypoint_leader.sh
        volumes:
            - /mnt:/opt/pilosa/data
        ports:
          - target: 10101
            published: 10101
            protocol: tcp
            mode: host
          - target: 11101
            published: 11101
            protocol: tcp
            mode: host
          - target: 15001
            published: 15001
            protocol: tcp
            mode: host
    pilosa-workers:
        image: audience-pilosa:latest
        networks:
        - pilosanetwork
        depends_on:
        - pilosa-leader
        deploy:
            replicas: ${NUM_WORKERS}
            placement:
                max_replicas_per_node: 1
            endpoint_mode: dnsrr
        entrypoint: ./entrypoint_worker.sh
        volumes:
            - /mnt:/opt/pilosa/data
        ports:
          - target: 10101
            published: 10101
            protocol: tcp
            mode: host
          - target: 11101
            published: 11101
            protocol: tcp
            mode: host
          - target: 15001
            published: 15001
            protocol: tcp
            mode: host

networks:
    pilosanetwork:
        driver: overlay
        attachable: true
