version: '3.7'

services:
    pilosa_coordinator:
        image: pilosa/pilosa:latest
        networks:
        - pilosanetwork
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
        command: [
            "pilosa",
            "server",
            "--advertise="0.0.0.0:15001",
            "--cluster.coordinator=true",
            "--gossip.seeds=\"pilosa_workers:15001\"",
            "--data-dir=\"/opt/pilosa/data\""
        ]
        ulimits:
          nproc: 655350
          nofile:
            soft: 102400
            hard: 409600
        volumes:
            - /mnt:/opt/pilosa/data
        ports:
          - target: 10101
            published: 10101
            protocol: tcp
            mode: host
          - target: 11101
            published: 11101
            protocol: tcp
            mode: host
          - target: 15001
            published: 15001
            protocol: tcp
            mode: host
    pilosa_workers:
        image: pilosa/pilosa:latest
        networks:
        - pilosanetwork
        depends_on:
        - pilosa_coordinator
        deploy:
            replicas: ${NUM_WORKERS}
            placement:
                max_replicas_per_node: 1
            endpoint_mode: dnsrr
        command: [
            "pilosa",
            "server",
            "--advertise=\"0.0.0.0:15001\"",
            "--gossip.seeds=\"pilosa_coordinator:15001,pilosa_workers:15001\"",
            "--data-dir=\"/opt/pilosa/data\""
        ]
        ulimits:
          nproc: 655350
          nofile:
            soft: 102400
            hard: 409600
        volumes:
            - /mnt:/opt/pilosa/data
        ports:
          - target: 10101
            published: 10101
            protocol: tcp
            mode: host
          - target: 11101
            published: 11101
            protocol: tcp
            mode: host
          - target: 15001
            published: 15001
            protocol: tcp
            mode: host

networks:
    pilosanetwork:
        driver: overlay
        attachable: true
