version: '3.8'

services:
    pilosa-coordinator:
        image: pilosa/pilosa:latest
        networks:
        - pilosanetwork
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
        command: [
            'server',
            '--cluster.coordinator=true',
            '--bind=0.0.0.0:10101',
            '--advertise=0.0.0.0:15001',
            '--gossip.port=11101',
            '--data-dir=/opt/pilosa/data'
        ]
        volumes:
            - /mnt:/opt/pilosa/data
        ports:
          - target: 10101
            published: 10101
            protocol: tcp
            mode: host
          - target: 11101
            published: 11101
            protocol: tcp
            mode: host
          - target: 15001
            published: 15001
            protocol: tcp
            mode: host
    pilosa-workers:
        image: pilosa/pilosa:latest
        networks:
        - pilosanetwork
        depends_on:
        - pilosa-coordinator
        deploy:
            replicas: ${NUM_WORKERS}
            placement:
                max_replicas_per_node: 1
            endpoint_mode: dnsrr
        command: [
            'server',
            '--bind=0.0.0.0:10101',
            '--advertise=0.0.0.0:15001',
            '--gossip.port=11101',
            '--gossip.seeds=pilosa-coordinator:11101,pilosa-workers:11101',
            '--data-dir=/opt/pilosa/data'
        ]
        volumes:
            - /mnt:/opt/pilosa/data
        ports:
          - target: 10101
            published: 10101
            protocol: tcp
            mode: host
          - target: 11101
            published: 11101
            protocol: tcp
            mode: host
          - target: 15001
            published: 15001
            protocol: tcp
            mode: host

networks:
    pilosanetwork:
        driver: overlay
        attachable: true
